### ISSUE TITLE
Key input windows doesn't show up with gtk4

### ISSUE THREAD

**Issue by soratobukuroneko** [AlynxZhou/showmethekey#11]
Gtk3 version seems to work fine. But with Gtk4 version, trying to open the usage dialog from menu or enabling input monitoring doesn't do anything. I don't know how I could help debug that, if you could give me some instruction please.

Running sway 1.7 wlroots 0.15.1

**Comment by AlynxZhou** [comment]
Maybe you should try to build it with debug enabled, and run with `GTK_DEBUG=all ./showmethekey-gtk/showmethekey-gtk`, then try to get some logs with the same operations.

**Comment by soratobukuroneko** [comment]
I did with v1.7.3:

```sh
meson configure --buildtype debug --optimization g build
meson compile --clean -C build
meson compile -C build
GTK_DEBUG=all ./build/showmethekey-gtk/showmethekey-gtk
```

But there is no output at all. If I do the same with v1.6.3, I have debug output though.

**Comment by AlynxZhou** [comment]
try `G_MESSAGES_DEBUG=showmethekey-gtk ./build/showmethekey-gtk/showmethekey-gtk`

**Comment by soratobukuroneko** [comment]
I get the following when enabling and disabling it:

```
(showmethekey-gtk:22447): showmethekey-gtk-DEBUG: 21:24:49.626: Mode: composed.
(showmethekey-gtk:22447): showmethekey-gtk-DEBUG: 21:24:49.627: Timeout: 1000.
(showmethekey-gtk:22447): showmethekey-gtk-DEBUG: 21:24:49.627: Size: 1500x200.
(showmethekey-gtk:22447): showmethekey-gtk-DEBUG: 21:24:49.659: smtk_keys_emitter_start_async() called.
(showmethekey-gtk:22447): showmethekey-gtk-DEBUG: 21:24:49.678: Allocated size: 1500x200.
(showmethekey-gtk:22447): showmethekey-gtk-DEBUG: 21:24:49.678: Clickable area: x: 697, y: 0, w: 95, h: 46.
(showmethekey-gtk:22447): showmethekey-gtk-DEBUG: 21:24:50.668: Timer triggered, clear keys.
(showmethekey-gtk:22447): showmethekey-gtk-DEBUG: 21:24:51.670: Timer triggered, clear keys.
(showmethekey-gtk:22447): showmethekey-gtk-DEBUG: 21:24:52.672: Timer triggered, clear keys.
(showmethekey-gtk:22447): showmethekey-gtk-DEBUG: 21:24:53.249: Adding key: MouseLeft.
(showmethekey-gtk:22447): showmethekey-gtk-DEBUG: 21:24:53.445: smtk_keys_emitter_stop_async() called.
(showmethekey-gtk:22447): showmethekey-gtk-DEBUG: 21:24:53.529: smtk_keys_emitter_cli_on_complete() called.
```

**Comment by AlynxZhou** [comment]
That looks OK, I have no idea why it does not show, maybe you can try to run it with `GDK_BACKEND=x11` to see whether it works under xwayland?

**Comment by soratobukuroneko** [comment]
Mmmh I remember I used X11 apps once on sway, but I notice right now that it's broken on my system… I can't run any X11 app so I can't tell you, sorry.

**Comment by AlynxZhou** [comment]
Could you try the latest version and give some logs here? Thanks.

**Comment by soratobukuroneko** [comment]
Hey, I can't do it now. I'm currently setting up my gentoo system from scratch. I keep that on my todo list, though. So, I hope that I will have my new setup ready soon to check if I still have the issue or not.

**Comment by soratobukuroneko** [comment]
I just tested quickly v1.10.0 which is packaged in gentoo "community" repository (guru). And well, the key are shown and the usage dialog too. I guess I just had my system completly broken as I told you earlier
