### ISSUE TITLE
[Request] Please add option to show shift

### ISSUE THREAD

**Issue by 3dsf** [AlynxZhou/showmethekey#16]
Thanks for working on this project.

I think that when people are following along, 
they might miss the distinction between 
`r` and `R`, especially when it is a `Ctrl+r` vs `Ctrl+R`

Thanks

**Comment by AlynxZhou** [comment]
Could be done if I have time on this. Soon or later.

**Comment by AlynxZhou** [comment]
<https://github.com/AlynxZhou/showmethekey/commit/3e1be24a71a8a8890741e164ba6937fd9091b947>.
