### ISSUE TITLE
Show and hide Clickable Area with a switch or toggle click through with a switch

### ISSUE THREAD

**Issue by 3dsf** [AlynxZhou/showmethekey#17]
The `Clickable Area` might be confusing to video viewers.  
Replacing with an icon or darkening a corner may be better.  

Or renaming to `Key Display Area` might be appropriate.

**Comment by AlynxZhou** [comment]
> Or renaming to Key Display Area might be appropriate.

No, it means "you can only drag here to move the floating window". That's why it is called `Clickable Area`, other area is click-through.

Maybe using other difference to hint the area is OK, but needs a better idea.

**Comment by latipun7** [comment]
Sorry to necro-bump this issue.
Maybe an option to hide the `Clickable Area` would be preferred. So, user can still move the keys overlay, then hide that clickable area if the position is desirable, that way, the viewer didn't get bothered by `Clickable Area`.

**Comment by AlynxZhou** [comment]
> Sorry to necro-bump this issue. Maybe an option to hide the `Clickable Area` would be preferred. So, user can still move the keys overlay, then hide that clickable area if the position is desirable, that way, the viewer didn't get bothered by `Clickable Area`.

Maybe not the best solution, but worth trying, I'd try this if I have time, thanks.

**Comment by AlynxZhou** [comment]
Because compositor may not preserve window position on next shown, maybe the switch should be auto enable when the floating window shows up, instead of remember its state.

If anyone has a better idea, please tell me, it's worth trying.

**Comment by latipun7** [comment]
I'm fine with that. Whenever this app runs, the `Clickable Area` is shown by default. Didn't need to remember the previous state. IMO.

**Comment by AlynxZhou** [comment]
![image](https://user-images.githubusercontent.com/8444615/217136278-26235730-7597-44f2-bca9-9244135453b8.png)

Works like this, but I then have another idea that how about make window normal on show up and then use a switch to enable click through, so user can manually change window size.

**Comment by latipun7** [comment]
Yes. That would be great instead of show & hide the `Clickable Area`.
Also, the padding at the top and bottom could be same length as well as left and right.

**Comment by AlynxZhou** [comment]
> Also, the padding at the top and bottom could be same length as well as left and right.

I wish I could do this, but it's not padding, it's header bar, I just write some CSS to make it transparent and remove the split line. Setting header bar to NULL requires a remap of window, then you may lose your window position. You cannot remove header bar by default, because you need it to drag window, or call window manager menus, so that's the best I can do.

**Comment by AlynxZhou** [comment]
So now I have two branches: <https://github.com/AlynxZhou/showmethekey/tree/click-through-switch> and <https://github.com/AlynxZhou/showmethekey/tree/hide-handle>.

`click-through-switch` allows user manually move or resize the keys window, which is good, but it adds an extra step that requires user toggle the switch, we already have some extra steps before usable in Wayland.

I personally prefer it, but I am waiting for other people's opinions here.

**Comment by raffaem** [comment]
> So now I have two branches: https://github.com/AlynxZhou/showmethekey/tree/click-through-switch and https://github.com/AlynxZhou/showmethekey/tree/hide-handle.
> 
> `click-through-switch` allows user manually move or resize the keys window, which is good, but it adds an extra step that requires user toggle the switch, we already have some extra steps before usable in Wayland.
> 
> I personally prefer it, but I am waiting for other people's opinions here.

Yeah, I use a tiling window manager, and with the `[click-through-switch](https://github.com/AlynxZhou/showmethekey/tree/click-through-switch)` branch, I can both tile and resize the window that shows the key.

With master I could resize it, but I couldn't tile it.

Thanks.

**Comment by raffaem** [comment]
> > Or renaming to Key Display Area might be appropriate.
> 
> No, it means "you can only drag here to move the floating window". That's why it is called `Clickable Area`, other area is click-through.
> 
> Maybe using other difference to hint the area is OK, but needs a better idea.

Well, I'm tiling it to display it at the bottom of my screen, with its own space, and all the other windows around it, so I don't need any "click.-through" since there is no window beneath it

**Comment by 3dsf** [comment]
@AlynxZhou 

I prefer the ```click-through-switch``` version too.    

**Thank you**

**Comment by AlynxZhou** [comment]
I'll try to do this soon. Sorry for late reply.

**Comment by AlynxZhou** [comment]
Finished in <https://github.com/AlynxZhou/showmethekey/commit/b0a60131bf48ce7dbc9c0c9ff72ed8f96d5197cd>.
