### ISSUE TITLE
Switch keyboard layout 

### ISSUE THREAD

**Issue by theRoboxx** [AlynxZhou/showmethekey#19]
Hi there,

I'm using a german keyboard layout (QWERTZ) and notices that keys like ö, ü and ä are displayed as ;, [ and '. Is it possible to change the whole layout or can I map the displayed keys manually?

**Comment by AlynxZhou** [comment]
I think xkbcommon should handle this, if not, maybe I need to find how to make it work.

**Comment by AlynxZhou** [comment]
> I think xkbcommon should handle this, if not, maybe I need to find how to make it work.

Manually set keyboard layout is needed I think, but this is not so easy. We cannot get keyboard layout directly from GDK, and it depends on the display protocol, X11 and Wayland has different interface to get it. Even we could get `wl_keyboard`, I don't think compositor will tell you keyboard layout change if you are not in focus?

It seems the only way is let user set their keyboard layouts, I think xkbcommon read keymaps from some package like `xkeyboard-configs`, maybe creating a list to select is OK.

**Comment by AlynxZhou** [comment]
Using GDK to translate keycodes to keyvals is available, but you cannot control keyboard state, which means you can only show `Ctrl+Shift+1` instead of `Ctrl+Shift+!`.

**Comment by AlynxZhou** [comment]
libxkbcommon provides a way to query RMLVO rules for keymap, maybe that is OK to use.

**Comment by AlynxZhou** [comment]
![image](https://github.com/AlynxZhou/showmethekey/assets/8444615/37b9676d-9280-4955-b25f-e620be03119e)

I managed to add an option to choose keyboard layout and variant for xkbcommon, it still requires user to choose manually, but we have no way to get current system layout, also I think in practice one user only has one physical keyboard layout, so this is fine.

**Comment by AlynxZhou** [comment]
Should be supported by <https://github.com/AlynxZhou/showmethekey/commit/f3142140a82a3d24c400b5c572b3bb20e1f9037d>.

**Comment by AlynxZhou** [comment]
> I'm using a german keyboard layout (QWERTZ) and notices that keys like ö, ü and ä are displayed as ;, [ and '. Is it possible to change the whole layout or can I map the displayed keys manually?

Currently it only shows keycode name (not the character), but at least it is OK. If I have time, I could add them into replace table to show them, but not today.
