### ISSUE TITLE
Issue authenticating on wayland

### ISSUE THREAD

**Issue by soyuka** [AlynxZhou/showmethekey#2]
Hi,

There's an issue when I input the password it just says "Authentication failed": 

```
==== AUTHENTICATING FOR org.freedesktop.policykit.exec ====
Authentication is needed to run `/usr/bin/showmethekey-cli' as the super user
Authenticating as: soyuka
Password:
==== AUTHENTICATION FAILED ====
``` 

I'm on 5.13.7-arch1-1, sway 1.6.1 (wayland), journalctl says:

```
Aug 05 19:08:51 syk-xp5 polkitd[753]: Unregistered Authentication Agent for unix-process:413838:2875488 (system bus name :1.676, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Aug 05 19:08:50 syk-xp5 pkexec[413928]: soyuka: Error executing command as another user: Not authorized [USER=root] [TTY=unknown] [CWD=/home/soyuka/forks/core] [COMMAND=/usr/bin/showmethekey-cli]
Aug 05 19:08:50 syk-xp5 polkitd[753]: Operator of unix-process:413838:2875488 FAILED to authenticate to gain authorization for action org.freedesktop.policykit.exec for unix-process:413838:2875488 [showmethekey-gtk] (owned by unix-user:soyuka)
Aug 05 19:08:50 syk-xp5 kernel: audit: type=1101 audit(1628183330.976:2328): pid=413937 uid=1000 auid=1000 ses=1 msg='op=PAM:accounting grantors=pam_unix,pam_permit,pam_time acct="soyuka" exe="/usr/lib/polkit-1/polkit-agent-helper-1" hostname=? addr=? terminal=? res=success'
Aug 05 19:08:50 syk-xp5 polkit-agent-helper-1[413937]: pam_systemd_home(polkit-1:account): systemd-homed is not available: Unit dbus-org.freedesktop.home1.service not found.
``` 

Any ideas or ways to get more debugging informations?

**Comment by AlynxZhou** [comment]
This seems like you just typed your password incorrectly?

**Comment by mhdzli** [comment]
@proudmuslim-dev 

Install `polkit-gnome` in Arch-Linux use `sudo pacman -S polkit-gnome`. Then run `/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & showmethekey-gtk` [here](https://ttm.sh/ii0.mp4) is a video I record today

**Comment by lilydjwg** [comment]
Same here.

Installing `polkit-gnome` works for me too but it is a weird workaround. It shouldn't matter which agent is used.

**Comment by AlynxZhou** [comment]
I'll handle this soon, thanks.

**Comment by AlynxZhou** [comment]
Hi, do you guys all using simple compositors here (I mean, not DEs)? I think pkexec should fallback to its tty agent, but not sure why it does not work...

**Comment by mhdzli** [comment]
@AlynxZhou 
Hi
I'm using swaywm right now.
And I have this issue on dwl (another wlroots based compositor/window manager)

**Comment by AlynxZhou** [comment]
> @AlynxZhou Hi I'm using swaywm right now. And I have this issue on dwl (another wlroots based compositor/window manager)

What's the result of running `pkexec ls` in terminal?

**Comment by AlynxZhou** [comment]
I am afraid this is a known issue for pkexec, not my program, that all other authentication agent except itself works, see <https://github.com/NixOS/nixpkgs/issues/18012> and <https://gitlab.freedesktop.org/polkit/polkit/-/issues/17>.

A MR has been submitted recently and may fix this problem, see <https://gitlab.freedesktop.org/polkit/polkit/-/merge_requests/122/diffs>.

**Comment by mhdzli** [comment]
@AlynxZhou 
Yes you're right. It's the `pkexec` issue.
 
```
==== AUTHENTICATING FOR org.freedesktop.policykit.exec ====
Authentication is needed to run `/usr/bin/ls' as the super user
Authenticating as: mzeinali
Password: 
polkit-agent-helper-1: error response to PolicyKit daemon: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: No session for cookie
==== AUTHENTICATION FAILED ====
Error executing command as another user: Not authorized

This incident has been reported.
```

**Comment by STARRY-S** [comment]
Hi, maybe we can try to add the `cap_dac_override` capability for `showmethekey-cli` by executing:
```
sudo setcap cap_dac_override+eip /path/to/showmethekey-cli
```
and then remove `pkexec` in `g_subprocess_new`,
this might be a way to solve this problem :-)

**Comment by AlynxZhou** [comment]
I believe that asking root permission on start is better so user will get notified when the app starts.

**Comment by guyuming76** [comment]
> > @AlynxZhou Hi I'm using swaywm right now. And I have this issue on dwl (another wlroots based compositor/window manager)
> 
> What's the result of running `pkexec ls` in terminal?

I am using dwl. with

`sudo -EH showmethekey-gtk`

i can turn switch on.

The problem now is the window for display key is not always on top. I don't know how to fix it yet.
