### ISSUE TITLE
Keys ignored if device_name contains \n

### ISSUE THREAD

**Issue by XMadFoX** [AlynxZhou/showmethekey#21]
It breaks parsing:

```
(showmethekey-gtk:1812744): showmethekey-gtk-WARNING **: 22:39:24.556: Create event error: <data>:1:78: Parse error: scanner: unterminated string constant.

(showmethekey-gtk:1812744): showmethekey-gtk-WARNING **: 22:39:24.556: Create event error: <data>:1:8: Parse error: unexpected identifier `Line2', expected value.
```

`libinput list-devices` looks like

```
...
Device:           Line1
Line2
...
```

I think I might do PR to fix it

**Comment by AlynxZhou** [comment]
Well, when I started to write this app, I just decide to output a json per
line…Never think about device name contains \n, there are some solutions in
my brain, I'll handle tomorrow.

**Comment by AlynxZhou** [comment]
I just dropped device name totally.
