### ISSUE TITLE
../meson.build:87:8: ERROR: Program 'gtk4-update-icon-cache' not found or not executable

### ISSUE THREAD

**Issue by guyuming76** [AlynxZhou/showmethekey#24]
i am building showmethekey from source with commands in README.md and get the error in this title.

I use gentoo linux.

what is the "gtk4-update-icon-cache"?

i have package dev-util/gtk-update-icon-cache installed, version 3.24.31

i also have gui-libs/gtk 4.8.3 installed, but i wonder if i missed any USE flag for this.

**Comment by AlynxZhou** [comment]
> i have package dev-util/gtk-update-icon-cache installed, version 3.24.31

This looks like a GTK3 version, you need the one for GTK4.

**Comment by AlynxZhou** [comment]
Closed because of no response. I think it should be fixed on the user's Gentoo setup.
