### ISSUE TITLE
Custom keyboard layout

### ISSUE THREAD

**Issue by Nora-n** [AlynxZhou/showmethekey#25]
Hi,

First of all thank you for this awesome piece of software! Having all the possible keyboard layouts is great too.

However, I've remapped some of my keyboard keys to some other functions thanks to `xmodmap`, so `showmethekey` doesn't get the actual input.

Would it be possible to give this layout to the software? I'm not sure about the way it works, but that would be just fantastic.

Have a great day!

**Comment by AlynxZhou** [comment]
Currently it is not able to do this, but I suggest to remap keys using udev (<https://wiki.archlinux.org/title/Map_scancodes_to_keycodes#Using_udev>) instead of X-related tools, this works not only under Xorg, but also Wayland and tty and others, it's in a deeper level.

**Comment by Nora-n** [comment]
Wow thanks for the fast reply! Would this make `showmethekey` show the actual input?

**Comment by AlynxZhou** [comment]
> Wow thanks for the fast reply! Would this make `showmethekey` show the actual input?

Yes

**Comment by Nora-n** [comment]
Thanks, have a good day!
