### ISSUE TITLE
Option to hide boxes around keys

### ISSUE THREAD

**Issue by DuckDuckWhale** [AlynxZhou/showmethekey#28]
The boxes are kinda ugly to look at. It would be great if there's an option to hide them and just have some gap between key combos.

**Comment by AlynxZhou** [comment]
It could be done when I have time, but

> The boxes are kinda ugly to look at.

those words make me unhappy because I spend a lot of time on writing code to do custom drawing, if you don't like them, just say you don't like them. I personally like those borders.

**Comment by AlynxZhou** [comment]
![image](https://github.com/AlynxZhou/showmethekey/assets/8444615/841f5c3e-92a0-4a12-bee9-f7522f17a1c3)

This is what you prefer uh?

**Comment by AlynxZhou** [comment]
![image](https://github.com/AlynxZhou/showmethekey/assets/8444615/15e839b2-ee8a-4cd4-8180-d7a3a9f5e2a4)

Or even better, all texts are sitting on the baseline if no border box, I'll push it soon.

**Comment by AlynxZhou** [comment]
Closed by <https://github.com/AlynxZhou/showmethekey/commit/9272dec607bc3ebb48bf25804ac88268f47485e6>.
