### ISSUE TITLE
Doesn't understand Capslock bound to Escape

### ISSUE THREAD

**Issue by DuckDuckWhale** [AlynxZhou/showmethekey#29]
As a Vim user I mapped my Capslock to Escape in Gnome. This program didn't pick that up and every time I pressed Escape (My "Capslock") it shows Capslock and then all my keystrokes become uppercase. This might be a bit hard to implement because (if I understand it correctly) this reads directly from the input devices, so if it's too hard a toggle button for this configuration would be nice too.

**Comment by David-Else** [comment]
@DuckDuckWhale https://github.com/rvaiya/keyd works on Wayland at least. I am pressing caps lock here using the supplied default script:


![image](https://github.com/AlynxZhou/showmethekey/assets/12832280/5f021292-1403-404c-9294-ec386f6d7931)

```sh
[ids]

*

[main]

# Maps capslock to escape when pressed and control when held.
capslock = overload(control, esc)
```
