### ISSUE TITLE
Suggestion for mouse clicks

### ISSUE THREAD

**Issue by Rmano** [AlynxZhou/showmethekey#32]
Hi!

First of all, thank you for this app, which is a life-saver for preparing screencasts in Linux. It works well, is well-documented, and is the only one I managed to use for a screencast for my gnome extension.

A suggestion: it is true that the mouse clicks "can be very annoying" 😉 (as you say in the configuration windows). It would be better to have small icons with the mouse and the pressed key backed out, similar to what [KmCaster](https://flathub.org/apps/com.whitemagicsoftware.kmcaster) does --- but with the scrolling events like in your app, which is much more useful for understanding what the user is doing.

**Comment by AlynxZhou** [comment]
I am not so good at illustrating...I'll do this, but have no plan currently.

**Comment by AlynxZhou** [comment]
I think this could also be solved by the newly added compact display mode in v1.13.0, which uses smaller icons for mouse and will merge new key if it is the same as the last key, so it will be less annoying.
