### ISSUE TITLE
clickable margin/padding is staing after i remove clickable tick from setting its look weird

### ISSUE THREAD

**Issue by RuddraNickBiswas** [AlynxZhou/showmethekey#36]
![image](https://github.com/AlynxZhou/showmethekey/assets/63276603/c132be8e-5800-477b-947e-6bac9f593a24)

**Comment by AlynxZhou** [comment]
It is window headerbar, and window should have a headerbar, though you could remove headerbar while running, it will require a re-map and may drop the always on top, so I have to keep the headerbar.

And I think you should not make that window so small, normally the headerbar is not so large and could be ignore... or maybe make it smaller? Why you want to make the window so small?

**Comment by AlynxZhou** [comment]
Closed as no response.
