### ISSUE TITLE
Integrate with Mechvibes [Feature Request]

### ISSUE THREAD

**Issue by iitzrohan** [AlynxZhou/showmethekey#37]
Thank you for this wonderful app. As I've been using it, I've come to appreciate that it's the only application that fully supports native Wayland. 
The experience has been exceptional, and I believe it could become even better If we could have the simulated mechanical keyboard and mouse click sounds integrated into this app.
Currently no app provides this feature on wayland.
It would truly become an all-in-one native Wayland multipurpose application.

**Comment by AlynxZhou** [comment]
> It would truly become an all-in-one native Wayland multipurpose application.

Anyone blocks you from running 2 apps at the same time?

> I believe it could become even better If we could have the simulated mechanical keyboard and mouse click sounds integrated into this app.

This is totally unrelated with the purpose of this project ("Show" me the key, not "Speak" me the key). It will be hard to maintain those two different features in one project, and not every user of this app needs that.

> Currently no app provides this feature on wayland.

It will be better if you ask Mechvibes to add support for Wayland, or write your own alternative in a dependent project, it could use the same way to get keyboard events like this app.
