### ISSUE TITLE
单独的 ctrl+shift 没有被视为组合键

### ISSUE THREAD

**Issue by yuzhen1024** [AlynxZhou/showmethekey#39]
当【显示模式】为按键名时，【单独显示】不会生效。
当【显示模式】为组合键时，【单独显示】生效，但问题在于，ctrl+shift 不会被视为组合键，也不会显示出来你按下了该按键，这包括【单独显示】在没有打开的状态。

**Comment by AlynxZhou** [comment]
按键名会直接显示所有按键，不考虑组合键，所以单独显示没有影响。

然后单独显示是指比如说是显示 Shift+A 还是只有 A，目前组合键的逻辑是 修饰键+普通按键，Ctrl+Shift 视作只按了两个修饰键，没有按下普通按键的话就认为是无效组合不显示。这个也许可以改，但我得想想怎么做。

**Comment by AlynxZhou** [comment]
这个应该还是没法支持，不然比如输入 Ctrl+Shift+A 的时候不好判断是 Ctrl+Shift 还是 Ctrl+Shift+A。
