### ISSUE TITLE
disabled Width and Height

### ISSUE THREAD

**Issue by rodrigopim** [AlynxZhou/showmethekey#40]
My distro is fedora 38 and i can't change size of keystroke area.

obs: 
It Can be add a abbreviation view? Delete -> Del and icon for Enter and Backspace?

**Comment by AlynxZhou** [comment]
> My distro is fedora 38 and i can't change size of keystroke area.

You could drag the window like other normal window before turn off `Clickable` switch.

> It Can be add a abbreviation view? Delete -> Del and icon for Enter and Backspace?

Let's track this in <https://github.com/AlynxZhou/showmethekey/issues/42>, so I could close this issue.

**Comment by AlynxZhou** [comment]
> It Can be add a abbreviation view? Delete -> Del and icon for Enter and Backspace?

Check the compact display mode added in v1.13.0.

**Comment by rodrigopim** [comment]
> > It Can be add a abbreviation view? Delete -> Del and icon for Enter and Backspace?
> 
> Check the compact display mode added in v1.13.0.

Finally, I was able to update (because I was preparing to update for the FC40) and it was really cool!
