### ISSUE TITLE
Compact view

### ISSUE THREAD

**Issue by SailReal** [AlynxZhou/showmethekey#42]
It would be really cool to have a compact view like in Screenkey e.g. `Space` could be displayed as `␣`

![image](https://github.com/AlynxZhou/showmethekey/assets/1786772/8ed04fa5-ae87-4aaa-9fab-e30dc534e323)

or e.g. `Right` by `→`

![image](https://github.com/AlynxZhou/showmethekey/assets/1786772/118f61dc-5dbb-4ee3-9a7d-a9dd61742e93)

Even more advanced would be if I type `␣` twice, it prints `␣`x2

**Comment by AlynxZhou** [comment]
I personally do not interest in this, but many people asked for it. I can try to implement when I have time.

**Comment by AlynxZhou** [comment]
Implemented in v1.13.0 as compact display mode. Closed.
