### ISSUE TITLE
不适配系统浅色模式，文字和窗口背景撞色

### ISSUE THREAD

**Issue by chiyuki0325** [AlynxZhou/showmethekey#45]
桌面：KDE 6.0

![图片](https://github.com/AlynxZhou/showmethekey/assets/73830635/b5339ffe-21fe-4793-84ac-c1d64df89dc5)

**Comment by AlynxZhou** [comment]
这个窗口背景不应该这么浅的，你是什么版本？重新安装一下试试？

**Comment by AlynxZhou** [comment]
现在怎么样了？

**Comment by chiyuki0325** [comment]
是自定义 gtk 主题导致，删除 ~/.config/gtk-4.0 修复
