### ISSUE TITLE
[Feature Request] Show only invisible keys

### ISSUE THREAD

**Issue by iolo** [AlynxZhou/showmethekey#46]
For screen cast, 
We need an another option to show only invisible keys(combination with modifier keys).
(Hide alphabet, numeric and symbol keys those are visible in editor)
And another option to show mouse clicks with modifier(ex. Ctrl+click).

**Comment by AlynxZhou** [comment]
Should be easy to implement when I have time.

**Comment by iolo** [comment]
Here is a quick and dirty patch:
https://github.com/iolo/showmethekey/tree/feat/show-visible-keys-only

I’ll make a PR with some clean up.

**Comment by AlynxZhou** [comment]
> Here is a quick and dirty patch: https://github.com/iolo/showmethekey/tree/feat/show-visible-keys-only
> 
> I’ll make a PR with some clean up.

This should be done in keys mapper, in which we can know whether modifier is active, and I already have a basic implementation, I'll finish it this afternoon.

**Comment by AlynxZhou** [comment]
Ideally we should filter out insertable keys between functional keys (Keys like F1-F12 are invisible, right?), but xkbcommon doesn't provide such a function, and it is hard to implement it by ourselves, the keysyms are not continuous, you cannot simply filter them by range, so let's just show keys with modifiers.

**Comment by AlynxZhou** [comment]
Done via <https://github.com/AlynxZhou/showmethekey/commit/e84a8d0207541fc6ea4306e09561bc28f49a547c>.
