### ISSUE TITLE
[Feature Request] Add feature to stay on top of GNOME overview

### ISSUE THREAD

**Issue by amethystgosling** [AlynxZhou/showmethekey#48]
... so we can show our key input there.

**Comment by AlynxZhou** [comment]
No, it is not allowed by design, overview will put GNOME Shell on top of all windows.

**Comment by amethystgosling** [comment]
> No, it is not allowed by design, overview will put GNOME Shell on top of all windows.

Should I make a feature request on gnome-shell for the overview to let screenkey software windows be "Always On Top" of it because screenkey sofware should? Or should this be handled by some new portal so that it works for all fullscreen launchers that don't let any windows be on top?

**Comment by AlynxZhou** [comment]
> > No, it is not allowed by design, overview will put GNOME Shell on top of all windows.
> 
> My idea is that I should make a feature request on gnome-shell Gitlab for them to let the overview let some windows like screenkey software windows be "Always On Top" of it because some software needs to show over a fullscreen launcher/ overview.
> 

I don't think they will allow this, it obeys the design.

> Or maybe I should request the Freedesktop devs to develop a portal for this instead so it works on every launcher in any DE that implements the portal.
> 
> Which one of these requests do you think I should make?

I am not familiar with portal, but you may try to ask them.
