### ISSUE TITLE
After disabling 'Clickable' keys view window still uses space ineficiently

### ISSUE THREAD

**Issue by toboil-features** [AlynxZhou/showmethekey#54]
There is no difference in font's height occupation if I disable clickable view. I haven't found the setting to fix it, so I am here.
It is useful if I need to make that window slim, because I am required to.

Clickable is enabled:
![Clickable enabled](https://github.com/user-attachments/assets/525926a6-6272-4b6e-9fd5-1871bcebaf90)
Clickable is disabled:
![Clickable disabled](https://github.com/user-attachments/assets/af735a0a-8bc5-4709-9d6c-c675e637dd7c)

© Art by axo1otl "Scarlet Tree"

**Comment by toboil-features** [comment]
#52

**Comment by AlynxZhou** [comment]
Don't know why I commented out that line.

Should be fixed by <https://github.com/AlynxZhou/showmethekey/commit/9438137f32c7d9cf212a5f8c872b66d3779df080>.
