### ISSUE TITLE
Ability to start Keys window without starting Settings window

### ISSUE THREAD

**Issue by toboil-features** [AlynxZhou/showmethekey#55]
I want to start program with Keys window automatically, without enabling it all the time when I start ShowMeTheKey.
I see it as a setting which toggles such thing and as an argument like --keys-window.

**Comment by AlynxZhou** [comment]
Worth trying.

**Comment by AlynxZhou** [comment]
See <https://github.com/AlynxZhou/showmethekey/commit/cd4f13fb1cda81103adba81ef0f2495e660062f5`>.

Run it with `showmethekey-gtk --active`.

**Comment by toboil-features** [comment]
Are there any ability to hide settings window? I wish it will be not shown, if not closed.

**Comment by toboil-features** [comment]
And, thank you for your project. It really helps me to record keys.
