### ISSUE TITLE
Have a trouble at compiling latest commit

### ISSUE THREAD

**Issue by toboil-features** [AlynxZhou/showmethekey#56]
The Meson build system
Version: 1.5.1
Source dir: /home/user/showmethekey
Build dir: /home/user/showmethekey/build
Build type: native build
Project name: showmethekey
Project version: 1.13.1
C compiler for the host machine: cc (gcc 14.2.1 "cc (GCC) 14.2.1 20240910")
C linker for the host machine: cc ld.bfd 2.43.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Configuring config.h using configuration
Found pkg-config: YES (/usr/bin/pkg-config) 2.1.1
Run-time dependency libevdev found: YES 1.13.3
Run-time dependency libudev found: YES 256
Run-time dependency libinput found: YES 1.26.2
Run-time dependency threads found: YES
Run-time dependency gtk4 found: YES 4.14.5
Run-time dependency libadwaita-1 found: YES 1.5.3
Run-time dependency x11 found: YES 1.8.10
Run-time dependency glib-2.0 found: YES 2.80.5
Run-time dependency json-glib-1.0 found: YES 1.10.1
Run-time dependency gio-2.0 found: YES 2.80.5
Run-time dependency cairo found: YES 1.18.2
Run-time dependency pango found: YES 1.54.0
Run-time dependency xkbcommon found: YES 1.7.0
Run-time dependency xkbregistry found: YES 1.7.0
Dependency gio-2.0 found: YES 2.80.5 (cached)
Program /usr/bin/glib-compile-resources found: YES (/usr/bin/glib-compile-resources)
Dependency glib-2.0 found: YES 2.80.5 (cached)
Program /usr/bin/glib-mkenums found: NO

../showmethekey-gtk/meson.build:52:19: ERROR: Dependency 'glib-2.0' tool variable 'glib_mkenums' contains erroneous value: '/usr/bin/glib-mkenums'

This is a distributor issue -- please report it to your glib-2.0 provider.

I am on Arch

**Comment by AlynxZhou** [comment]
> This is a distributor issue -- please report it to your glib-2.0 provider.
> 
> I am on Arch

<https://aur.archlinux.org/packages/showmethekey#comment-979185>

Install `glib2-devel` because Arch decide to split the package.
