### ISSUE TITLE
Minimal height is 200px

### ISSUE THREAD

**Issue by toboil-features** [AlynxZhou/showmethekey#58]
Month ago there were no issue with it, but now it presents.
I can't make keys window smaller than 200 pixels in height.

Sitting under latest commit.

**Comment by DuncanMcRae** [comment]
I think the text height is also tied to the this, making the font enormous on a 1080p monitor

**Comment by AlynxZhou** [comment]
Fixed by <https://github.com/AlynxZhou/showmethekey/commit/fa4c79e4f4e76a7614968225a19adf91f2e0f137>.
