### ISSUE TITLE
Font size is enormous, and can't be changed

### ISSUE THREAD

**Issue by DuncanMcRae** [AlynxZhou/showmethekey#59]
Font size fills the entire height of the window. At 200px, this is too much on a 1080p monitor; I don't want to have the window stretch hz across my entire screen so users can read what's going on. You should be able to reduce the size of the window so you can get 12pt font - or something like that.

**Comment by AlynxZhou** [comment]
Previously you can reduce the window height, but after some update of GTK it limits minimal window height to 200px, and I don't find where to remove the limitation, once I know this will be fixed.

**Comment by cafreo** [comment]
the issue seems to occur since libadwaita 1.6. downgrading to 1.5.4 fixed it for me

**Comment by AlynxZhou** [comment]
> the issue seems to occur since libadwaita 1.6. downgrading to 1.5.4 fixed it for me

Let me check what is changed between those two versions.

**Comment by AlynxZhou** [comment]
https://gitlab.gnome.org/GNOME/libadwaita/-/commit/7a705c7959d784fa6d40af202d5d06d06f1e2fa6

OK. Let me overwrite it.

**Comment by AlynxZhou** [comment]
![image](https://github.com/user-attachments/assets/859a72f1-5e59-463b-8f41-9538e327e85d)

Done.

**Comment by AlynxZhou** [comment]
Fixed by <https://github.com/AlynxZhou/showmethekey/commit/fa4c79e4f4e76a7614968225a19adf91f2e0f137>.
