### ISSUE TITLE
Toggle Pause outside of Settings Menu

### ISSUE THREAD

**Issue by Hexygo** [AlynxZhou/showmethekey#60]
Hi, love the project, i was messing around with it and wanted to use it while streaming, so it would be optimal if i could temporarily switch of the logging of the keys without having to go into the settings application and click on pause, for instance just like screenkey does

> To disable screenkey while recording (for example, during password prompts),
> press both control keys, or both shift keys, or both alt keys at the same time.
> Press the same combination again to resume it.

Would you consider adding this feature? Thanks

**Comment by AlynxZhou** [comment]
I think I could implement this when I have time, thanks.

**Comment by AlynxZhou** [comment]
Done via <https://github.com/AlynxZhou/showmethekey/commit/51ea179065e239f3e69486bdf3fe03ac67874217>.

**Comment by AlynxZhou** [comment]
I only support press both alt to toggle pause, I think this is enough?

**Comment by Hexygo** [comment]
Yes, thank you!
